### ISSUE TITLE
Некорректное отображение.

### ISSUE THREAD

**Issue by dimterex** [anticodeninja/antilogviewer#1]
1. Если в строку выводить полностью Exception.
2. Если в строку выводить очень длинную строку.

**Comment by anticodeninja** [comment]
Hi, @dimterex! Thanks for your feedback!
What was done:
1. Multiline exceptions squashed into one line with cool "⮐" sign. It allows to use a space effectively, avoiding performance reduction.
2. A full message with all line-wrappings is shown on a tooltip when a mouse is pointed over a log line.
I hope this helps.
