### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by dimterex** [anticodeninja/antilogviewer#11]
Можно ли добавить контекстное меню, которе содержит в себе несколько пунктов, а именно:
1. добавить источник в игнор. лист
2. добавить источник в фильтрацию
3. добавить возможность выделять цветом данный источник в таблице.

**Comment by dimterex** [comment]
4. Добавлять любой элемент из иерархии в фильтр. Расширение 1-2 пункта.

**Comment by anticodeninja** [comment]
It looks like everything is done.
