### ISSUE TITLE
Source Filter Element we can see all text in one string

### ISSUE THREAD

**Issue by gusgene** [anticodeninja/antilogviewer#18]
![image](https://user-images.githubusercontent.com/40135457/74621698-6f142680-5170-11ea-93b0-23b15f57efb8.png)

**Comment by gusgene** [comment]
We need to create a several filter source strings (more than 5)? save our profile, restart application and open our saved profile.

**Comment by anticodeninja** [comment]
@gusgene Thanks for the scenario! I finally able to reproduce the issue and fix it! Please try new version from AppVeyor and if everything fine I will close the issue.

**Comment by anticodeninja** [comment]
The issue was fixed.
