### ISSUE TITLE
When switch my theme from light to dark or vice versa bottom panel stay at previous color

### ISSUE THREAD

**Issue by gusgene** [anticodeninja/antilogviewer#23]

**Comment by gusgene** [comment]
![image](https://user-images.githubusercontent.com/40135457/90598591-8619fb00-e21d-11ea-9ed5-a66f7dd0e946.png)

**Comment by anticodeninja** [comment]
It was the expected behavior... But it's fixed. Maybe not in expected way, but the whole block is redesigned and the issue is not actual anymore.

**Comment by gusgene** [comment]
Accepted
